import type { Metadata } from "next";
import { Pacifico, Kiwi_Maru } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
    variable: '--font-pacifico',
    subsets: ['latin', 'cyrillic'],
    weight: '400',
    style: 'normal'
});

const kiwimaru = Kiwi_Maru({
    variable: '--font-kiwimaru',
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body
                className={`${pacifico.variable} ${kiwimaru.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
