import type { Metadata } from "next";
import { Pacifico, Kiwi_Maru, Marck_Script, Klee_One, Arimo } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
    variable: '--font-pacifico',
    subsets: ['latin', 'cyrillic'],
    weight: '400',
    style: 'normal'
});

const kiwimaru = Kiwi_Maru({
    variable: '--font-kiwimaru',
    subsets: ['latin'],
    weight: '300',
});

const marck = Marck_Script({
    variable: '--font-marck',
    subsets: ['latin'],
    weight: '400'
})

const klee = Klee_One({
    variable: '--font-klee',
    weight: '400',
    subsets: ['latin', 'cyrillic']
})

const arimo = Arimo({
    variable: '--font-arimo',
    subsets: ['cyrillic', 'latin'],
    weight: '400'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth no-touch">
            <body
                className={`${pacifico.variable} ${kiwimaru.variable} ${marck.variable} ${klee.variable} ${arimo.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
